name: Code coverage

on:
  - push
  - pull_request

jobs:
  codecov:
    name: Code coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Run vet
        run: |
          go vet .
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
      - name: Run tests
        run: make cov
        env:
          COSYVOICE_API_KEY: ${{ secrets.COSYVOICE_API_KEY }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
